name: Release Apple backend

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Prepare Apple backend release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Build Apple backend
        if: ${{ steps.release.outputs.release_created == 'true' }}
        working-directory: backends/apple
        run: swift build --configuration release

      - name: Create Swift Package Archive
        if: ${{ steps.release.outputs.release_created == 'true' }}
        working-directory: backends/apple
        run: swift package archive-source

      - name: Upload archive to GitHub release
        if: ${{ steps.release.outputs.release_created == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd backends/apple
          gh release upload "${{ steps.release.outputs.tag_name }}" ./*.zip --clobber
